apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: video-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/adityarajput6421/K8_repo
    targetRevision: HEAD
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
